export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FLIGHT_DATE_REQUEST = 'FLIGHT_DATE_REQUEST';
export const FLIGHT_DATE_SUCCESS = 'FLIGHT_DATE_SUCCESS';
export const FLIGHT_DATE_FAILURE = 'FLIGHT_DATE_FAILURE';
export const FLIGHT_DATE_CLEAR = 'FLIGHT_DATE_CLEAR';

export const FLIGHT_DATE_ADD_FAVORITE = 'FLIGHT_DATE_ADD_FAVORITE';
export const FLIGHT_DATE_REMOVE_FAVORITE = 'FLIGHT_DATE_REMOVE_FAVORITE';
export const FLIGHT_DATE_CLEAR_FAVORITE = 'FLIGHT_DATE_CLEAR_FAVORITE';
