export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';

export const FLIGHT_DATE_REQUEST = 'FLIGHT_DATE_REQUEST';
export const FLIGHT_DATE_SUCCESS = 'FLIGHT_DATE_SUCCESS';
export const FLIGHT_DATE_FAILURE = 'FLIGHT_DATE_FAILURE';


